;
    // insert(&root,3);
    // insert(&root,4);
    // insert(&root,5);
    // insert(&root,6);
    // insert(&root,7);
    // insert(&root,8);
    // insert(&root,9);
    // insert(&root,10);
    // inorder(&root);
    // findData(&root, 10);